### ISSUE TITLE
ModuleNotFoundError: No module named 'loss_classes' how to resolve this. Please help

### ISSUE THREAD

**Issue by bindujiit** [Tandon-A/emotic#10]
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from train import train_emotic
  File "/content/gdrive/MyDrive/Deep learning Models/emotic-master/emotic-master/train.py", line 16, in <module>
    from loss_classes import DiscreteLoss, ContinuousLoss_SL1, ContinuousLoss_L2
ModuleNotFoundError: No module named 'loss_classes'

**Comment by sumit0309** [comment]
Could you please let me know how did you resolve this error?
