### ISSUE TITLE
AttributeError: Can't get attribute 'Emotic' on <module '__main__' from 'main.py'>

### ISSUE THREAD

**Issue by JASCRAJ** [Tandon-A/emotic#15]
while loading pretrained 'model_emotic1.pth'
getting this error

mode  inference
Traceback (most recent call last):
  File "main.py", line 102, in <module>
    inference_emotic(args.inference_file, model_path, result_path, context_norm, body_norm, ind2cat, ind2vad, args)
  File "E:\emotic-master\inference.py", line 110, in inference_emotic
    emotic_model = torch.load(os.path.join(model_path,'model_emotic1.pth')).to(device)
  File "C:\Python\Python36\lib\site-packages\torch\serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Python\Python36\lib\site-packages\torch\serialization.py", line 851, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'Emotic' on <module '__main__' from 'main.py'>

**Comment by Tandon-A** [comment]
@JASCRAJ 
Hello, 
Thanks for bringing this issue to my notice. 
I have fixed the same. You can take a pull of the updated code. 

Regards, 
Abhishek
